trigger:
- desenv

jobs:

  - job: 'Test'
    pool:
      vmImage: 'vs2017-win2016'
    strategy:
      matrix:
        Python37:
          python.version: '3.7'
      maxParallel: 1

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '${python.version}'
          architecture: 'x64'
      - script: pip install -r requirements.txt && npm install chromedriver
        displayName: 'Install dependencies'
      - powershell: robot -d results  ./src/ui/
        displayName: 'Run robot scenarios'